---
version: 3
images:
  base_image:
    name: registry.access.redhat.com/ubi9/python-39:latest

dependencies:
  galaxy:
    collections:
      - name: ansible.eda
      - name: smartgic.eda

  python:
    - azure-servicebus
    - aiobotocore
    - aiohttp
    - aiokafka
    - watchdog
    - systemd-python
    - dpath
    - ansible-rulebook
    - pan-python
    - xmltodict
    - paramiko

  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner

  system:
    - systemd-devel [platform:rpm]
    - python3.11-devel [platform:rpm]
    - java-17-openjdk-devel [platform:rpm]

  python_interpreter:
    package_system: python3.11
    python_path: /usr/bin/python3.11

additional_build_steps:
  append_final:
    - 'RUN chown -R default:root /opt/app-root/src && chmod 777 /opt/app-root/src/.ansible'
