---
- name: Demo rules with websocket as source
  hosts: all

  sources:
    - name: websocket
      smartgic.eda.websocket:
        host: "{{ websocket_host | default('127.0.0.1') }}"
        port: "{{ websocket_port | default(8181) }}"
        path: "{{ websocket_path | default('/core') }}"

  rules:
    - name: Check for message type
      condition: event.type == "ovos-skill-personal.OpenVoiceOS:WhoMadeYou.intent"
      action:
        debug:
