---
- name: Demo rules with websocket as source
  hosts: all

  sources:
    - name: websocket
      smartgic.eda.websocket:
        host: "{{ webspcket_host | default('127.0.0.1') }}"
        port: "{{ webspcket_port | default(8181) }}"
        path: "{{ webspcket_path | default('/core') }}"

  rules:
    - name: Run job template
      condition: event.type == "skill-ovos-hello-world.openvoiceos.activate"
      action:
        run_job_template:
          name: ovos-history
          organization: Default
          job_args:
            extra_vars:
              name: Gaëtan
          retries: 2
          delay: 10
